stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

gt-checksum_build_x86:
  stage: build
  retry: 2
  only:
    - master
    - v1.2.2
  tags:
    - dbomb-golangci-lint
  script:
    - /bin/bash build.sh x86_64
  artifacts:
    paths:
      - release/
    expire_in: 7 days

gt-checksum_build_arm:
  stage: build
  retry: 2
  only:
    - master
    - v1.2.2
  tags:
    - dbomb-golangci-lint
  script:
    - /bin/bash build.sh aarch64
  artifacts:
    paths:
      - release/
    expire_in: 7 days
