stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

gt_checkout_build_x86:
  stage: build
  retry: 2
  only:
    - schedules
    - master
  tags:
    - gt-tools-builder-x86
  script:
    - /bin/bash build-x86.sh
  artifacts:
    paths:
      - binary/
    expire_in: 30 days

gt_checkout_build_arm:
  stage: build
  retry: 2
  only:
    - schedules
    - master
  tags:
    - gt-tools-builder-arm
  script:
    - /bin/bash build-arm.sh
  artifacts:
    paths:
      - binary/
    expire_in: 30 days