[DSNs]
;oracle的连接串为 oracle|user/password@ip:port/sid
;mysql的连接串为 mysql|usr:password@tcp(ip:port)/dbname?charset=xxx
srcDSN = mysql|pcms:abc123@tcp(172.17.140.212:3306)/information_schema?charset=utf8
dstDSN = mysql|pcms:abc123@tcp(172.17.140.232:3306)/information_schema?charset=utf8

[Schema]
tables = %pcms%.*
ignore-tables = %pcms.*
checkNoIndexTable = yes
lowerCaseTableNames = no

[Logs]
log = E:\万里开源\goProject\greatdbCheck\src\greatdbCheck\gt-checkOut.log
logLevel = info

[Rules]
parallel-thds = 5
singleIndexChanRowCount = 10
jointIndexChanRowCount = 10
queue-size = 100
checkMode = rows
checkObject = data
ratio = 1


[Repair]
datafix = file
fixFileName = E:\万里开源\goProject\greatdbCheck\src\greatdbCheck\gt-checkOutDataFix.sql
