[DSNs]
;oracle的连接串为 oracle|user/password@ip:port/sid
;mysql的连接串为 mysql|usr:password@tcp(ip:port)/dbname?charset=xxx
;destJdbc = oracle|pcms/abc123@172.17.140.232:1521/helowin
;sourceJdbc = mysql|pcms:abc123@tcp(172.17.140.212:3306)/information_schema?charset=utf8
;srcDSN = oracle|aa/abc123@172.17.140.232:1521/helowin
;dstDSN = mysql|aa:abc123@tcp(172.17.140.212:3306)/information_schema?charset=utf8
;sourceJdbc = oracle|zx/zx@172.16.50.83:1521/zx
;destJdbc = mysql|greatdb:!QAZ2wsx@tcp(172.16.50.81:3306)/information_schema?charset=utf8
;srcDSN = mysql|yejr:yejr@tcp(172.17.140.123:3306)/test?charset=latin1
;dstDSN = mysql|yejr:yejr@tcp(172.17.140.123:4306)/test?charset=utf8
;srcDSN = mysql|pcms:abc123@tcp(172.17.140.232:3307)/information_schema?charset=utf8
dstDSN = oracle|scott/tiger@172.17.140.73:1521/orcl
srcDSN = mysql|pcms:abc123@tcp(172.17.140.232:3307)/information_schema?charset=utf8

[Schema]
tables = scott.bmsql_order_line_1
;tables = pcms.a5
ignore-tables =
checkNoIndexTable = yes
lowerCaseTableNames = no

[Logs]
log = ./gt-checkOut.log
logLevel = info

[Rules]
parallel-thds = 10 
singleIndexChanRowCount = 10000
jointIndexChanRowCount = 10000
queue-size = 100
checkObject = data
checkMode = rows
ratio = 100


[Repair]
datafix = file
fixTrxNum = 100
fixFileName = ./gt-checkOutDataFix.sql
