[Source Destination connection]
;oracle的连接串为 oracle|user/password@ip:port/sid
;mysql的连接串为 mysql|usr:password@tcp(ip:port)/dbname?charset=xxx
sourceJdbc = oracle|pcms/abc123@172.17.140.47:1521/helowin
destJdbc = mysql|root:abc123@tcp(172.17.140.222:3306)/information_schema?charset=utf8

[Database Conn Pool Setting]
poolMin = 100
poolMax = 100

[Detection object]
schema = pcms
table = pcms.gobench1
ignoreSchema = a
ignoreTable = a.aA
checkNoIndexTable = yes
lowerCaseTableNames = no

[Log Setting]
logPath = E:\万里开源\goProject\greatdbCheck\src\greatdbCheck
logFile = gt-checkOut.log
logLevel = info

[CheckSum Rules]
concurrency = 15
singleIndexChanRowCount = 1000
jointIndexChanRowCount = 1000
queueDepth = 100
checkMode = rows
checkObject = data
ratio = 1

[increment Data Check]
incSwitch = yes
incStopGtidNum = 0
incStopTrTime =

[Sql Repair]
datafix = table
fixPath = E:\万里开源\goProject\greatdbCheck\src\greatdbCheck
fixFileName = gt-checkOutDataFix.sql